apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic.fullname" . }}-secret
data:
  RESTIC_PASSWORD: {{ required "resticPassword is required" .Values.resticPassword | b64enc }}
  AWS_ACCESS_KEY_ID: {{ required "s3.accessKey is required" .Values.s3.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ required "s3.secretKey is required" .Values.s3.secretKey | b64enc}}
